apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - image: ${DATETIME}
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
            - containerPort: 8080
          resources: {}
status: {}
---
