apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}-deployment  # 添加后缀避免命名冲突
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - image: ${IMAGE_REPO}
          imagePullPolicy: Always
          name: ${APP_NAME}-container  # 容器名添加后缀
          ports:
            - containerPort: 80  # 改为标准 Web 端口
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"